### ISSUE TITLE
Question about procedural displacement

### ISSUE THREAD

**Issue by TD22057** [YgabrielsY/sispo#253]
Thanks for doing this and making it open source.  I was hoping to play with the Itokawa demo and experiment with different procedural terrain parameters.  In the PLOS One paper, it says that SISPO supports automatic surface generation and mentions input parameters ("The size of these features, their number and their distribution can be adjusted by modifying the corresponding parameters.").  I've been looking through the code and wasn't able to find these settings anywhere.    I was wondering if I'm missing something or is assumed that you do that step manually yourself? 

Thanks,
Ted

**Comment by oknuutti** [comment]
I only contributed the OpenGL version, but to my understanding, the surface generation for Blender-based rendering is defined using material nodes, which are contained in the .blend files, located at data/models. At least the sssb.blend has these nodes. I'm currently unable to locate the Itokawa model though. Could another contributor with more experience with Blender find it?

BR,
Olli

**Comment by TD22057** [comment]
Thanks.  I think the basic one is the sssb file will be good enough to get an idea how it works.

**Comment by andris-space** [comment]
Hey Ted, Thanks for your interest! As you see, SISPO as many similar tools
do not have a proper interface which is making the learning curve rather
steep. We have ideas of developing a mission design tool which would have a
graphical interface but this will obviously take a lot of effort. At any
rate, we see that deep-space cubesats will need optical "AutoNav"
navigation, like Deep Space 1 demonstrated already in the late 90s, which
in turn needs real time modelling of the space scene. Our colleagues from the
ULYSSES team have already used Unreal Engine 5 for lunar rover navigation
<https://space-travel.blog/ulysses-1f4342d04f66> in real time simulations.
In a mission like ESTCube-3 (not much is public yet) which we're planning
for lunar orbit, ULYSSES-like capabilities will be necessary for orbital
stuff to develop and test navigation algorithms. The main problem is that
SISPO cannot account for operational changes in the scene: like a rover
making decisions based on the surrounding scene and leaving tracks or like
ESTCube-3 performing attitude and orbital maneuvers which also changes the
scene.

Cheers,
Andris
